model:
  base_learning_rate: 1.0e-06
  target: ldm.models.diffusion.ddpm.LatentDiffusion
  params:
    linear_start: 0.0015
    linear_end: 0.0205
    log_every_t: 100
    timesteps: 1000
    loss_type: l1
    first_stage_key: image
    cond_stage_key: condition
    image_size: 64
    channels: 3
    concat_mode: true
    monitor: val/loss

    unet_config:
      target: ldm.modules.diffusionmodules.documbinmodel.UNetModel
      params:
        image_size: 64
        in_channels: 6
        out_channels: 3
        model_channels: 256
        attention_resolutions:
        # note: this isn\t actually the resolution but
        # the downsampling factor, i.e. this corresnponds to
        # attention on spatial resolution 8,16,32, as the
        # spatial reolution of the latents is 64 for f4
        - 8
        - 4
        - 2
        num_res_blocks: 2
        channel_mult:
        - 1
        - 2
        - 3
        - 4
        num_head_channels: 8
        resblock_updown: true
    first_stage_config:
      target: ldm.models.autoencoder.VQModelInterface
      params:
        ckpt_path: weights/ae/new_16.ckpt
        embed_dim: 3
        n_embed: 8192
        ddconfig:
          attn_type: none
          double_z: false
          z_channels: 3
          resolution: 256
          in_channels: 1
          out_ch: 1
          ch: 128
          ch_mult:
          - 1
          - 2
          - 4
          num_res_blocks: 2
          attn_resolutions: []
          dropout: 0.0
        lossconfig:
          target: ldm.modules.losses.contperceptual.DummyLoss
    cond_stage_config: __is_first_stage__
data:
  target: main.DataModuleFromConfig
  params:
    batch_size: 1
    num_workers: 64
    wrap: false
    train:
      target: ldm.data.binary.CustomTrain
      params:
        training_images_list_file: data/train_3.txt
        size: 256
    validation:
      target: ldm.data.binary.CustomTest
      params:
        test_images_list_file: data/test_3.txt
        size: 256

